import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'

import Card from "../components/Card";

import styles from '../styles/Home.module.css'


const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {/* Welcome to <a href="https://nextjs.org">Next.js!</a> */}
        </h1>
        
        <Link href="/ox"><a>Ox's page</a></Link>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          
          <div className={styles.grid}>
            <Card/>
            <Card/>
            <Card/>
          </div>
          
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://twitter.com/bowtiedcicada"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by autism.
        </a>
      </footer>
    </div>
  )
}

export default Home
